// #define MOUSE_EXTENDED_REPORT
// #define POINTING_DEVICE_ROTATION_90
// #define POINTING_DEVICE_ROTATION_180
#define POINTING_DEVICE_ROTATION_270
// #define POINTING_DEVICE_INVERT_X
// #define POINTING_DEVICE_INVERT_Y

#define CIRQUE_PINNACLE_DIAMETER_MM 40

#define CIRQUE_PINNACLE_CURVED_OVERLAY

#define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_RELATIVE_MODE

#define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_2X